### ISSUE TITLE
Upload to maven central

### ISSUE THREAD

**Issue by jalexcole** [Gleethos/neureka#24]
Have this project uploaded into maven central for easy use.

**Comment by Gleethos** [comment]
Maybe we are not talking about the same maven, but I have already uploaded to maven through sonatype,
which you can find [here](https://search.maven.org/artifact/com.github.gleethos/neureka/1.0.0/jar) or [here](https://mvnrepository.com/artifact/com.github.gleethos/neureka).

So you can then easily add Neureka as dependency in the config of your build system of choice:
```
<dependency>
  <groupId>com.github.gleethos</groupId>
  <artifactId>neureka</artifactId>
  <version>1.0.0</version>
</dependency>
```
or Gradle
```
implementation 'com.github.gleethos:neureka:1.0.0'
```
or Groovy Grape
```
@Grapes(
  @Grab(group='com.github.gleethos', module='neureka', version='1.0.0')
)
```
...etc

**Comment by jalexcole** [comment]
I found it.
