### ISSUE TITLE
Button Overhaul

### ISSUE THREAD

**Issue by mischulz14** [Gleethos/neureka#4]
I've noticed that the design of the navigation button is a bit outdated imo, can I try to redesign them? 

![image](https://user-images.githubusercontent.com/96014669/195988200-ba8275a2-f370-480a-9a0c-0ed1a02dcbe0.png)

**Comment by Gleethos** [comment]
Hey! Yeah I agree. I made the site a couple of years ago and the whole navigation UI
definitely needs some overhaul.

**Comment by mischulz14** [comment]
Which branch should I fork?

**Comment by Gleethos** [comment]
Simply fork the master branch and I will merge your redesign when you are ready! 

Thanks for wanting to contribute! :)
